language: go

go:
  - 1.2
  - 1.4
  - tip

before_install:
  - go get
  - mysql -e 'create database Domaniator;'
  - cat Layout.sql | mysql
  

script:
  - go build
  - ./Domainiator -input list.txt
  - mysql -e "SELECT * FROM Domaniator.Results"
  - cd cron
  - go build
  - ./cron
